[ospf_routers]
router2 ansible_host=10.10.10.1 router_id=2.2.2.2
router3 ansible_host=10.10.10.5 router_id=3.3.3.3
router4 ansible_host=10.10.10.9 router_id=4.4.4.4
router5 ansible_host=10.10.10.13 router_id=5.5.5.5
router6 ansible_host=10.10.10.17 router_id=6.6.6.6

[ospf_routers:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios
ansible_user=CCNA      
ansible_password=Cisco
